import tw from "twrnc";
import { IBaseLayout, IColors } from "@Themes/interfaces";

export const Theme = (colors: IColors): IBaseLayout => ({
  __THEMENAME: colors.__THEMENAME,
  width: {
    full: tw`w-full`,
    half: tw`w-1/2`,
    quarter: tw`w-1/4`,
  },
  height: {
    full: tw`h-full`,
    half: tw`h-1/2`,
    quarter: tw`h-1/4`,
  },
  flex: {
    flex: tw`flex`,
    grow: tw`flex-grow`,
    shrink: tw`flex-shrink`,
    direction: {
      row: tw`flex-row`,
      column: tw`flex-col`,
    },
    wrap: tw`flex-wrap`,
    alignItems: {
      start: tw`items-start`,
      center: tw`items-center`,
      end: tw`items-end`,
    },
    alignContent: {
      start: tw`content-start`,
      center: tw`content-center`,
      end: tw`content-end`,
    },
    justifyContent: {
      start: tw`justify-start`,
      center: tw`justify-center`,
      end: tw`justify-end`,
      between: tw`justify-between`,
      evenly: tw`justify-evenly`,
    },
    basis: {
      half: {
        flexBasis: "50%",
      },
      quarter: {
        flexBasis: "25%",
      },
      third: {
        flexBasis: "33%",
      },
      threeQuarters: {
        flexBasis: "75%",
      },
    },
    alignSelf: {
      start: tw`self-start`,
      center: tw`self-center`,
      end: tw`self-end`,
    },
  },
  padding: {
    top: {
      none: tw`pt-0`,
      xxxsmall: tw`pt-1`,
      xxsmall: tw`pt-2`,
      xsmall: tw`pt-3`,
      small: tw`pt-4`,
      medium: tw`pt-5`,
      large: tw`pt-6`,
      xlarge: tw`pt-7`,
      xxlarge: tw`pt-8`,
      xxxlarge: tw`pt-9`,
    },
    right: {
      none: tw`pr-0`,
      xxxsmall: tw`pr-1`,
      xxsmall: tw`pr-2`,
      xsmall: tw`pr-3`,
      small: tw`pr-4`,
      medium: tw`pr-5`,
      large: tw`pr-6`,
      xlarge: tw`pr-7`,
      xxlarge: tw`pr-8`,
      xxxlarge: tw`pr-9`,
    },
    bottom: {
      none: tw`pb-0`,
      xxxsmall: tw`pb-1`,
      xxsmall: tw`pb-2`,
      xsmall: tw`pb-3`,
      small: tw`pb-4`,
      medium: tw`pb-5`,
      large: tw`pb-6`,
      xlarge: tw`pb-7`,
      xxlarge: tw`pb-8`,
      xxxlarge: tw`pb-9`,
    },
    left: {
      none: tw`pl-0`,
      xxxsmall: tw`pl-1`,
      xxsmall: tw`pl-2`,
      xsmall: tw`pl-3`,
      small: tw`pl-4`,
      medium: tw`pl-5`,
      large: tw`pl-6`,
      xlarge: tw`pl-7`,
      xxlarge: tw`pl-8`,
      xxxlarge: tw`pl-9`,
    },
    all: {
      none: tw`p-0`,
      xxxsmall: tw`p-1`,
      xxsmall: tw`p-2`,
      xsmall: tw`p-3`,
      small: tw`p-4`,
      medium: tw`p-5`,
      large: tw`p-6`,
      xlarge: tw`p-7`,
      xxlarge: tw`p-8`,
      xxxlarge: tw`p-9`,
    },
    horizontal: {
      none: tw`px-0`,
      xxxsmall: tw`px-1`,
      xxsmall: tw`px-2`,
      xsmall: tw`px-3`,
      small: tw`px-4`,
      medium: tw`px-5`,
      large: tw`px-6`,
      xlarge: tw`px-7`,
      xxlarge: tw`px-8`,
      xxxlarge: tw`px-9`,
    },
    vertical: {
      none: tw`py-0`,
      xxxsmall: tw`py-1`,
      xxsmall: tw`py-2`,
      xsmall: tw`py-3`,
      small: tw`py-4`,
      medium: tw`py-5`,
      large: tw`py-6`,
      xlarge: tw`py-7`,
      xxlarge: tw`py-8`,
      xxxlarge: tw`py-9`,
    },
  },
  margin: {
    top: {
      none: tw`mt-0`,
      xxxsmall: tw`mt-1`,
      xxsmall: tw`mt-2`,
      xsmall: tw`mt-3`,
      small: tw`mt-4`,
      medium: tw`mt-5`,
      large: tw`mt-6`,
      xlarge: tw`mt-7`,
      xxlarge: tw`mt-8`,
      xxxlarge: tw`mt-9`,
    },
    right: {
      none: tw`mr-0`,
      xxxsmall: tw`mr-1`,
      xxsmall: tw`mr-2`,
      xsmall: tw`mr-3`,
      small: tw`mr-4`,
      medium: tw`mr-5`,
      large: tw`mr-6`,
      xlarge: tw`mr-7`,
      xxlarge: tw`mr-8`,
      xxxlarge: tw`mr-9`,
    },
    bottom: {
      none: tw`mb-0`,
      xxxsmall: tw`mb-1`,
      xxsmall: tw`mb-2`,
      xsmall: tw`mb-3`,
      small: tw`mb-4`,
      medium: tw`mb-5`,
      large: tw`mb-6`,
      xlarge: tw`mb-7`,
      xxlarge: tw`mb-8`,
      xxxlarge: tw`mb-9`,
    },
    left: {
      none: tw`ml-0`,
      xxxsmall: tw`ml-1`,
      xxsmall: tw`ml-2`,
      xsmall: tw`ml-3`,
      small: tw`ml-4`,
      medium: tw`ml-5`,
      large: tw`ml-6`,
      xlarge: tw`ml-7`,
      xxlarge: tw`ml-8`,
      xxxlarge: tw`ml-9`,
    },
    all: {
      none: tw`m-0`,
      xxxsmall: tw`m-1`,
      xxsmall: tw`m-2`,
      xsmall: tw`m-3`,
      small: tw`m-4`,
      medium: tw`m-5`,
      large: tw`m-6`,
      xlarge: tw`m-7`,
      xxlarge: tw`m-8`,
      xxxlarge: tw`m-9`,
    },
    horizontal: {
      none: tw`mx-0`,
      xxxsmall: tw`mx-1`,
      xxsmall: tw`mx-2`,
      xsmall: tw`mx-3`,
      small: tw`mx-4`,
      medium: tw`mx-5`,
      large: tw`mx-6`,
      xlarge: tw`mx-7`,
      xxlarge: tw`mx-8`,
      xxxlarge: tw`mx-9`,
    },
    vertical: {
      none: tw`my-0`,
      xxxsmall: tw`my-1`,
      xxsmall: tw`my-2`,
      xsmall: tw`my-3`,
      small: tw`my-4`,
      medium: tw`my-5`,
      large: tw`my-6`,
      xlarge: tw`my-7`,
      xxlarge: tw`my-8`,
      xxxlarge: tw`my-9`,
    },
  },
  colors: {
    background: colors.background,
  },
  font: {
    colors: colors.font,
    size: {
      xsmall: tw`text-xs`,
      small: tw`text-sm`,
      medium: tw`text-base`,
      large: tw`text-lg`,
      xlarge: tw`text-xl`,
    },
    weight: {
      light: tw`font-light`,
      regular: tw`font-normal`,
      medium: tw`font-medium`,
      bold: tw`font-bold`,
    },
  },
});
